# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Deploy bookdown output to netlify

on:
  push:
    branches:
      - 'main'
      paths:
        - 'docs/**'

name: netlify

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir _book
